// import { Footer, Header } from "@/components";
// import { iranSans } from "@/utils/fonts";
// import type { Metadata } from "next";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// export default function RootLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode;
// }>) {

//     return (
//         <html 
//             lang="en" 
//             suppressHydrationWarning 
//             className={` |  |  | scroll-smooth overflow-x-hidden`}
//         >
//             <body className={`relative main-selection | bg-body-bg-light dark:bg-body-bg-dark ${iranSans} |  | `}>
//                 <Header />
//                 {children}
//                 <Footer />
//             </body>
//         </html>
//     );

// }

import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { iranSans, } from "@/utils/fonts";
import { Footer, Header } from "@/components";
import TanstackProvider from "@/providers/TanstackProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html 
            lang="en" 
            suppressHydrationWarning
            className={` |  |  | scroll-smooth overflow-x-hidden`}
        >
            <body className={`relative main-selection | bg-body-bg-light dark:bg-body-bg-dark ${iranSans} |  | `}>
                <ThemeProvider defaultTheme="dark" storageKey="next-theme">
                    <TanstackProvider>
                        <Header />
                        {children}
                        <Footer />
                    </TanstackProvider>
                </ThemeProvider>
            </body>
        </html>
    );

}
